# Generated by Django 4.2.11 on 2024-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookList_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='BookList_AP_price_89e5cd_idx')],
            },
        ),
    ]
